---
- name: Copy dockerconfigjson for github registry
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/kube/secret/dockerconfigjson.yaml"
    dest: "/tmp/dockerconfigjson.yaml"

- name: Create secret for github registry
  shell: |
    sudo kubectl create -f /tmp/dockerconfigjson.yaml
