kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
  labels:
    app: sample-app
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJaV3hwWlcxdmNtbGpaV0YxT21kb2NGOUhWbXd6WW1KU1IwaDBjV2RxY0RrM2FsSlZOVTFHTkZsWmJqTndNRUl5YVVSSE0zaz0ifX19
