grafana:
  ingress:
    ## If true, Grafana Ingress will be created
    ##
    enabled: true

    ## IngressClassName for Grafana Ingress.
    ## Should be provided if Ingress is enable.
    ##
    ingressClassName: nginx

    ## Annotations for Grafana Ingress
    ##
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

    ## Labels to be added to the Ingress
    ##
    labels: {}

    ## Hostnames.
    ## Must be provided if Ingress is enable.
    ##
    hosts:
      - control-plane-vm-iac.westeurope.cloudapp.azure.com

    ## Path for grafana ingress
    path: /dashboard

    ## TLS configuration for grafana Ingress
    ## Secret must be manually created in the namespace
    ##
    tls:
      - secretName: "grafana-tls"
        hosts:
          - control-plane-vm-iac.westeurope.cloudapp.azure.com

  grafana.ini:
    security:
      cookie_secure: false
    server:
      domain: control-plane-vm-iac.westeurope.cloudapp.azure.com
      protocol: http
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/dashboard/"
      serve_from_sub_path: true
  
  sidecar:
    datasources:
      enabled: true
    dashboards:
      enabled: true

  # Configuration additionnelle pour Loki
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local
      version: 1
      editable: false
      jsonData:
        httpHeaderName1: "X-Scope-OrgID"
      secureJsonData:
        httpHeaderValue1: "tenet1"
  
  dashboards:
    default:
      logs-dashboard:
        json: |
          {
            "annotations": {
              "list": [
                {
                  "builtIn": 1,
                  "datasource": {
                    "type": "grafana",
                    "uid": "-- Grafana --"
                  },
                  "enable": true,
                  "hide": true,
                  "iconColor": "rgba(0, 211, 255, 1)",
                  "name": "Annotations & Alerts",
                  "type": "dashboard"
                }
              ]
            },
            "editable": true,
            "fiscalYearStartMonth": 0,
            "graphTooltip": 0,
            "id": 28,
            "links": [],
            "panels": [
              {
                "datasource": {
                  "type": "loki",
                  "uid": "P8E80F9AEF21F6940"
                },
                "gridPos": {
                  "h": 8,
                  "w": 12,
                  "x": 0,
                  "y": 0
                },
                "id": 3,
                "options": {
                  "dedupStrategy": "none",
                  "enableLogDetails": true,
                  "prettifyLogMessage": false,
                  "showCommonLabels": false,
                  "showLabels": false,
                  "showTime": false,
                  "sortOrder": "Descending",
                  "wrapLogMessage": false
                },
                "targets": [
                  {
                    "datasource": {
                      "type": "loki",
                      "uid": "P8E80F9AEF21F6940"
                    },
                    "editorMode": "code",
                    "expr": "{namespace=\"monitoring\"}",
                    "queryType": "range",
                    "refId": "A"
                  }
                ],
                "title": "Logs Monitoring",
                "type": "logs"
              },
              {
                "datasource": {
                  "type": "loki",
                  "uid": "P8E80F9AEF21F6940"
                },
                "gridPos": {
                  "h": 8,
                  "w": 12,
                  "x": 12,
                  "y": 0
                },
                "id": 2,
                "options": {
                  "dedupStrategy": "none",
                  "enableLogDetails": true,
                  "prettifyLogMessage": false,
                  "showCommonLabels": false,
                  "showLabels": false,
                  "showTime": false,
                  "sortOrder": "Descending",
                  "wrapLogMessage": false
                },
                "targets": [
                  {
                    "datasource": {
                      "type": "loki",
                      "uid": "P8E80F9AEF21F6940"
                    },
                    "editorMode": "code",
                    "expr": "{namespace=\"ingress-nginx\"}",
                    "queryType": "range",
                    "refId": "A"
                  }
                ],
                "title": "Logs Nginx",
                "type": "logs"
              },
              {
                "datasource": {
                  "type": "loki",
                  "uid": "P8E80F9AEF21F6940"
                },
                "gridPos": {
                  "h": 8,
                  "w": 12,
                  "x": 0,
                  "y": 8
                },
                "id": 1,
                "options": {
                  "dedupStrategy": "none",
                  "enableLogDetails": true,
                  "prettifyLogMessage": false,
                  "showCommonLabels": false,
                  "showLabels": false,
                  "showTime": false,
                  "sortOrder": "Descending",
                  "wrapLogMessage": false
                },
                "targets": [
                  {
                    "datasource": {
                      "type": "loki",
                      "uid": "P8E80F9AEF21F6940"
                    },
                    "editorMode": "code",
                    "expr": "{namespace=\"argocd\"}",
                    "legendFormat": "",
                    "queryType": "range",
                    "refId": "A"
                  }
                ],
                "title": "Logs ArgoCD",
                "type": "logs"
              },
              {
                "datasource": {
                  "type": "loki",
                  "uid": "P8E80F9AEF21F6940"
                },
                "gridPos": {
                  "h": 8,
                  "w": 12,
                  "x": 12,
                  "y": 8
                },
                "id": 4,
                "options": {
                  "dedupStrategy": "none",
                  "enableLogDetails": true,
                  "prettifyLogMessage": false,
                  "showCommonLabels": false,
                  "showLabels": false,
                  "showTime": false,
                  "sortOrder": "Descending",
                  "wrapLogMessage": false
                },
                "targets": [
                  {
                    "datasource": {
                      "type": "loki",
                      "uid": "P8E80F9AEF21F6940"
                    },
                    "editorMode": "code",
                    "expr": "{namespace=\"apps\"}",
                    "queryType": "range",
                    "refId": "A"
                  }
                ],
                "title": "Logs Apps",
                "type": "logs"
              }
            ],
            "refresh": "5s",
            "schemaVersion": 39,
            "tags": [],
            "templating": {
              "list": []
            },
            "time": {
              "from": "now-6h",
              "to": "now"
            },
            "timepicker": {},
            "timezone": "browser",
            "title": "Logs",
            "uid": "eds2fmzgiq5fkf",
            "version": 1,
            "weekStart": ""
          }

loki:
  isDefault: false