apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "myapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "myapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: APP_DEBUG
              value: {{ .Values.env_app.APP_DEBUG }}
            - name: APP_ENV
              value: {{ .Values.env_app.APP_ENV }}
            - name: APP_KEY
              value: {{ .Values.env_app.APP_KEY }}
            - name: DB_CONNECTION
              value: {{ .Values.env_app.DB_CONNECTION }}
            - name: DB_HOST
              value: {{ .Values.env_app.DB_HOST }}
            - name: DB_PORT
              value: {{ .Values.env_app.DB_PORT }}
            - name: DB_DATABASE
              value: {{ .Values.env_app.DB_DATABASE }}
            - name: DB_USERNAME
              value: {{ .Values.env_app.DB_USERNAME }}
            - name: DB_PASSWORD
              value: {{ .Values.env_app.DB_PASSWORD }}
