- name: Helm repo add dependencies
  shell: |
    helm repo add argo https://argoproj.github.io/argo-helm
    helm repo add jetstack https://charts.jetstack.io
    helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
    helm repo update

# CertManager
#
#
- name: Install CertManager for SSL support
  shell: helm upgrade --install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --set installCRDs=true

- name: Copy Staging Issuer file
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/staging_issuer.yaml"
    dest: "/tmp/staging_issuer.yaml"
- name: Copy Prod Issuer file
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/prod_issuer.yaml"
    dest: "/tmp/prod_issuer.yaml"

- name: Install Issuers
  shell: |
    sudo kubectl apply -f /tmp/prod_issuer.yaml

# K8S Dashboard
#
#
- name: Install K8S Dashboard
  shell: helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard

# ArgoCD
#
#
- name: Copy ArgoCD values file
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/argocd-values.yaml"
    dest: "/tmp/argocd-values.yaml"

- name: Copy ArgoCD ingress file
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/argocd-nginx-ingress.yaml"
    dest: "/tmp/argocd-nginx-ingress.yaml"

- name: Copy K8S ingress file
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/k8s-dashboard-nginx-ingress.yaml"
    dest: "/tmp/k8s-dashboard-nginx-ingress.yaml"

- name: Install with Helm
  shell: helm upgrade --install --create-namespace -n argocd argocd argo/argo-cd -f /tmp/argocd-values.yaml

- name: Install Ingress
  shell: |
    sudo kubectl apply -f /tmp/argocd-nginx-ingress.yaml
    sudo kubectl apply -f /tmp/k8s-dashboard-nginx-ingress.yaml


- name: Change All service type to LoadBalancer
  shell: |
    sudo kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
    sudo kubectl patch svc kubernetes-dashboard-kong-proxy -n kubernetes-dashboard -p '{"spec": {"type": "LoadBalancer"}}'

- name: Create Service Account for K8S Dashboard and token
  shell: |
    sudo kubectl -n kubernetes-dashboard create serviceaccount k8s-adm
    sudo kubectl -n kubernetes-dashboard create token k8s-adm
    
- name: Start port forwarding for NGINX Ingress Controller LoadBalancer Service
  shell: |
    sudo kubectl port-forward service/ingress-nginx-controller-loadbalancer -n ingress-nginx 80:80 --address 0.0.0.0 2>&1 >/dev/null &
    sudo kubectl port-forward service/ingress-nginx-controller-loadbalancer -n ingress-nginx 443:443 --address 0.0.0.0 2>&1 >/dev/null &
