- name: Create dedicated ArgoCD namespace
  k8s:
    api_version: v1
    kind: Namespace
    name: "argocd"
    state: present
  run_once: yes

- name: Helm repo add argo
  become: true
  shell: |
    helm repo add argo https://argoproj.github.io/argo-helm
    helm repo update
    helm install -n argocd argocd argo/argo-cd