{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs Monitoring",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"monitoring\"}"
    }
   ]
  },
  {
   "title": "Logs Nginx",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"ingress-nginx\"}"
    }
   ]
  },
  {
   "title": "Logs ArgoCD",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{namespace=\"argocd\"}"
    }
   ]
  },
  {
   "title": "Logs Apps",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{namespace=\"apps\"}"
    }
   ]
  }
 ]
}