apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: app
          image: ghcr.io/msc1-nan24/t-clo-app:latest
          ports:
            - containerPort: 80
          env:
            - name: APP_DEBUG
              value: "{{ .Values.debug }}"
            - name: APP_ENV
              value: "production"
            - name: APP_KEY
              value: "{{ .Values.appKey }}"
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: "{{ .Values.mysql.host }}"
            - name: DB_PORT
              value: "{{ .Values.mysql.port }}"
            - name: DB_DATABASE
              value: "{{ .Values.mysql.db }}"
            - name: DB_USERNAME
              value: "{{ .Values.mysql.username }}"
            - name: DB_PASSWORD
              value: "{{ .Values.mysql.password }}"

