apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/add-base-url: 'true'
    nginx.ingress.kubernetes.io/base-url: {{.Values.baseUrl}}
spec:
  ingressClassName: nginx
  rules:
    - host: control-plane-vm-iac.westeurope.cloudapp.azure.com
      http:
        paths:
          - pathType: Prefix
            path: {{.Values.baseUrl}}
            backend:
              service:
                name: app-service
                port:
                  number: 80
  tls:
    - hosts:
        - control-plane-vm-iac.westeurope.cloudapp.azure.com
      secretName: app-server-tls
