---
- name: Install and configure Loki and Promtail for Kubernetes logging
  hosts: master
  vars:
    loki_namespace: "monitoring"
    loki_release_name: "loki"
    loki_chart_version: "6.6.6"
    loki_values_file: "loki-values.yaml"
    promtail_release_name: "promtail"
    promtail_chart_version: "6.15.3"
    kubeconfig: "/home/cloudtoto/.kube/config"

  tasks:
    - name: Setup Kubernetes environment
      include_tasks: tasks/kubernetes_setup.yml

    - name: Setup Helm repositories
      include_tasks: tasks/helm_setup.yml

    - name: Install and configure Loki
      include_tasks: tasks/loki_install.yml

    - name: Install and configure Promtail
      include_tasks: tasks/promtail_install.yml

    # - name: Configure Grafana for Loki
    #   include_tasks: tasks/grafana_config.yml