---
- name: Add Grafana Helm repository
  command: helm repo add grafana https://grafana.github.io/helm-charts
  register: helm_repo_add
  changed_when: "'has been added to your repositories' in helm_repo_add.stdout"

- name: Update Helm repositories
  command: helm repo update
  register: helm_repo_update
  changed_when: "'Update Complete' in helm_repo_update.stdout"