---
# - name: Check Loki Gateway service
#   command: kubectl --kubeconfig={{ kubeconfig }} get service loki-gateway -n {{ loki_namespace }}
#   register: loki_gateway_service
#   changed_when: false

# - name: Display Loki Gateway service details
#   debug:
#     var: loki_gateway_service.stdout_lines

- name: Get Loki service details
  command: >
    kubectl --kubeconfig={{ kubeconfig }} get service {{ loki_release_name }} 
    -n {{ loki_namespace }} 
    -o jsonpath='{.spec.clusterIP}'
  register: loki_service_ip

- name: Create Promtail values file
  template:
    src: promtail-values.yaml.j2
    dest: /home/cloudtoto/promtail-values.yaml

- name: Deploy Promtail using Helm
  command: >
    helm upgrade --install {{ promtail_release_name }} grafana/promtail
    --namespace {{ loki_namespace }}
    --version {{ promtail_chart_version }}
    -f /home/cloudtoto/promtail-values.yaml
  register: helm_install_promtail
  changed_when: "'STATUS: deployed' in helm_install_promtail.stdout"

- name: Wait for Promtail pods to be ready
  command: >
    kubectl --kubeconfig={{ kubeconfig }} wait --for=condition=ready pod 
    -l app.kubernetes.io/name=promtail
    -n {{ loki_namespace }}
    --timeout=300s
  register: promtail_pods_ready
  changed_when: false