- name: Get join token
  shell: kubeadm token create --print-join-command
  when: "inventory_hostname == 'cloudtoto@control-plane-vm-iac.westeurope.cloudapp.azure.com'"
  register: join_token_output
  become: yes
  run_once: yes

- set_fact:
    join_token: "{{ join_token_output.stdout }}"
  when: "inventory_hostname == 'cloudtoto@control-plane-vm-iac.westeurope.cloudapp.azure.com'"

- debug:
    var: join_token_output

- debug:
    var: inventory_hostname

- name: Check hostname resolution
  shell: ping -c 1 control-plane-vm-iac.westeurope.cloudapp.azure.com
  ignore_errors: yes
  register: ping_result
  when: "'worker' in inventory_hostname"

- name: Ensure hostname is reachable
  fail:
    msg: "Hostname 'control-plane-vm-iac.westeurope.cloudapp.azure.com' is not reachable. Check DNS configuration."
  when: "ping_result.rc != 0 and 'worker' in inventory_hostname"
  ignore_errors: yes

- name: Remove default contained config
  shell: |
    sudo rm /etc/containerd/config.toml
    sudo systemctl restart containerd
  when: "'worker' in inventory_hostname"

- name: Join worker nodes to the cluster
  become: yes
  shell: "{{ join_token_output.stdout }}"
  ignore_errors: yes
  when: "'worker' in inventory_hostname"