- name: Change hostname
  become: true
  hostname:
    name: "localhost"

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: apt

- name: Install docker
  import_tasks: docker.yaml
  when: '"docker-ce" not in ansible_facts.packages'

- name: Install kubeadm
  import_tasks: kubeadm.yaml
  when: '"kubeadm" not in ansible_facts.packages'

- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Initialize kubeadm
  when: "inventory_hostname == 'cloudtoto@control-plane-vm-iac.westeurope.cloudapp.azure.com'"
  import_tasks: init_kub.yaml
  run_once: yes

- name: Join the worker nodes
  import_tasks: join_kub.yaml
#- name: Join the worker nodes
#  import_tasks: join_kub.yaml
