- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: apt
- name: Install docker
  import_tasks: docker.yaml
  when: '"docker-ce" not in ansible_facts.packages'
- name: Install kubeadm
  import_tasks: kubeadm.yaml
  when: '"kubeadm" not in ansible_facts.packages'
- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca
- name: Initialize kubeadm
  import_tasks: init_kub.yaml
  when: not kubeadm_ca.exist
  run_once: yes
- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_kubelet
