---
- name: Add Prometheus Helm repository
  ansible.builtin.shell:
    cmd: |
      helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      helm repo update

- name: Install kube-prometheus-stack
  ansible.builtin.shell:
    cmd: |
      helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack -n monitoring --create-namespace
  args:
    creates: /usr/local/bin/prometheus