---
- name: Add Prometheus Helm repository
  ansible.builtin.shell:
    cmd: |
      helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      helm repo update

- name: Copy Grafana/Prometheus values file
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/grafana-values.yaml"
    dest: "/tmp/grafana-values.yaml"

- name: Install kube-prometheus-stack
  ansible.builtin.shell:
    cmd: |
      helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack -n monitoring --create-namespace -f /tmp/grafana-values.yaml
  args:
    creates: /usr/local/bin/prometheus


- name: Get Grafana password
  ansible.builtin.shell:
    cmd: sudo kubectl get secret --namespace monitoring kube-prometheus-stack-grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo
  register: grafana_password

- name: Save Grafana password
  local_action:
    module: copy
    content: "{{ grafana_password.stdout }}"
    dest: "{{ playbook_dir }}/credentials/grafana_password.txt"
