apiVersion: v2
name: t-clo-app
description: App for T-CLO-902 project
type: application
version: 1.0.4
appVersion: 1.0.4
maintainers:
  - name: T-CLOUD Team
    url: "https://github.com/Msc1-NAN24/T-CLOUD-INFRA"
home: "https://github.com/Msc1-NAN24/T-CLOUD-APP"
keywords:
  - app
  - epitech
  - sample-app
icon: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Epitech.png"
