---
#- name: Install CertManager for SSL support
#  hosts: master
#  roles:
#    - role: cert_manager
#
#- name: Install K8S Dashboard
#  hosts: master
#  roles:
#    - role: k8s_dashboard
#
#- name: Configure ArgoCD and Dependencies
#  hosts: master
#  roles:
#    - role: argocd

#- name: Install kube-prometheus on the cluster
#  hosts: master
#  roles:
#    - role: kube_prometheus


#- name: Install kube-dashboard
#  hosts: master
#  roles:
#    - role: k8s_dashboard

- name: Install loki and promtail on the cluster
  hosts: master
  vars:
    loki_namespace: "monitoring"
    loki_release_name: "loki"
    loki_chart_version: "6.6.6"
    loki_values_file: "loki-values.yaml"
    promtail_release_name: "promtail"
    promtail_chart_version: "6.15.3"
    kubeconfig: "/home/cloudtoto/.kube/config"
  roles:
    - role: loki

- name: Install kube-prometheus on the cluster
  hosts: master
  roles:
    - role: kube_prometheus


#- name: Install kube-prometheus on the cluster
#  hosts: master
#  roles:
#    - role: kube_prometheus
#
#- name: Install K8S Dashboard
#  hosts: master
#  roles:
#    - role: k8s_dashboard